version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - qqbot-net
    environment:
      TZ: Asia/Shanghai

  napcat:
    image: docker.1ms.run/mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6099:6099"
    restart: unless-stopped
    networks:
      - qqbot-net
    volumes:
      - ./data:/app/Eridanus/data:rw
      - ./napcat-cache:/app/napcat/cache:rw
      - ./run/group_fun/service:/app/Eridanus/run/group_fun/service:rw
    environment:
      DATA_ROOT: "/app/Eridanus/data"
      TZ: Asia/Shanghai

  eridanus:
    image: crpi-3gef5glpjhp2r3tx.cn-hangzhou.personal.cr.aliyuncs.com/sorahub/eridanus-docker:latest
    container_name: eridanus
    ports:
      - "5007:5007"
    restart: always
    depends_on:
      - redis
      - napcat
    networks:
      - qqbot-net
    volumes:
      - ./data:/app/Eridanus/data:rw
      - ./run/group_fun/service:/app/Eridanus/run/group_fun/service:rw
    environment:
      DATA_DIR: "/app/Eridanus/data"
      PICTURE_PATH: "/app/Eridanus/data/pictures"
      CACHE_PATH: "/app/Eridanus/data/video/cache"
      TZ: Asia/Shanghai

networks:
  qqbot-net:
    driver: bridge