today_wife:
  api:
  - 'http://127.0.0.1:5000/today_wife'  #今日老婆的获取api，可以替换成自己的图床，可以添加多个链接
  - 'https://api.iw233.cn/api.php?sort=top'
  header: 'https://weibo.com/'          #知道的自己改，不知道的不要动
  wifePrefix: '/'                       #透群友的指令前缀
  复读开关: True
  签🦌撤回: True
  透群友撤回: True
  透热门群友: True #只会透到最近发言较多的群友
  is_at: True #今日群友/管理/群主 是否艾特其本人