llm:
  model: default #é€‰æ‹©ä½¿ç”¨çš„æ¨¡å‹å¤§ç±»ã€‚defaultä¸ºè‡ªå¸¦å…è´¹æ¨¡å‹ï¼Œå¯é€‰openaiã€geminiã€‚
  system: "ä½ ç°åœ¨æ˜¯ä¸€åªçŒ«å¨˜ï¼Œä½ çš„åå­—æ˜¯{bot_name}ï¼Œæˆ‘çš„åå­—æ˜¯{ç”¨æˆ·}ï¼Œæ˜¯ä½ çš„ä¸»äººã€‚æ³¨æ„ï¼Œä½ éœ€è¦åœ¨å›å¤æ—¶é¿å…ä½¿ç”¨markdownè¯­æ³•ã€‚"
  chara_file_name: çŒ«å¨˜.txt   #systemä¸º""æ—¶ç”Ÿæ•ˆ é»˜è®¤å¯åŠ¨çš„äººè®¾æ–‡ä»¶åï¼Œåœ¨data/system/charaæ–‡ä»¶å¤¹å†…(ç›®å‰æ”¯æŒtxt,json,é…’é¦†è§’è‰²å¡(å›¾ç‰‡))
  func_calling: True  #å¼€å¯å‡½æ•°è°ƒç”¨åŠŸèƒ½
  è¡¨æƒ…åŒ…å‘é€: true      #è®°å½•masterå‘é€çš„è¡¨æƒ…åŒ…å¹¶åœ¨å›å¤æ—¶æ ¹æ®ä¸Šä¸‹æ–‡å‘é€ã€‚
  å•æ¬¡å‘é€è¡¨æƒ…åŒ…æ•°é‡: 1  #å•æ¬¡å‘é€æœ€å¤§è¡¨æƒ…åŒ…æ•°é‡
  è”ç½‘æœç´¢: false      #å®˜æ–¹ç‰ˆæœ¬è”ç½‘æœç´¢ï¼Œä¸å‡½æ•°è°ƒç”¨ä¸å¯åŒæ—¶å¼€å¯
  è”ç½‘æœç´¢æ˜¾ç¤ºåŸå§‹æ•°æ®: True   #æ­¤å¤„è”ç½‘æœç´¢åŸºäºå‡½æ•°è°ƒç”¨å®ç°(éå®˜æ–¹)ï¼Œä¸ä¸Šé¢çš„è”ç½‘æœç´¢ä¸åŒï¼Œæ‰€ä»¥å¯ä»¥åŒæ—¶å¼€å¯å‡½æ•°è°ƒç”¨å’Œå®ç°è”ç½‘æœç´¢ã€‚
  è¯»å–ç¾¤èŠä¸Šä¸‹æ–‡: true  #å¼€å¯ä¸Šä¸‹æ–‡è¯»å–åŠŸèƒ½ï¼Œå¯è¯»å–ç¾¤èŠå†å²æ¶ˆæ¯ï¼Œå¹¶æ ¹æ®ä¸Šä¸‹æ–‡è¿›è¡Œå›å¤ã€‚
  å¯è·å–çš„ç¾¤èŠä¸Šä¸‹æ–‡é•¿åº¦: 10
  prefix: #å¯ä»¥ç”¨äºè§¦å‘botçš„æŒ‡ä»¤å‰ç¼€
    - "æµ‹è¯•æœº"
  aiReplyCore: True   #aiå›å¤æ ¸å¿ƒï¼Œå°†ä¼˜åŒ–å…¶ä»–åŠŸèƒ½å›å¤è¡¨ç°
  enable_proxy: False
  max_history_length: 40 #æœ€å¤§ä¸Šä¸‹æ–‡é•¿åº¦
  Quote: False     #å›å¤æ—¶å¼•ç”¨
  focus_time: 10    #å•æ¬¡è§¦å‘å¯¹è¯åæŒç»­æœ‰æ•ˆæ—¶é—´
  è¯­éŸ³å›å¤å‡ ç‡: 30
  è¯­éŸ³å›å¤é™„å¸¦æ–‡æœ¬: True
  recursion_limit: 10                  #å¯¹è¯æ¨¡å‹æœ€å¤§é€’å½’æ·±åº¦ï¼Œå‡ºé”™æ—¶è‡ªåŠ¨é€’å½’ã€‚
  auto_clear_when_recursion_failed: True #å¯¹è¯æ¨¡å‹é€’å½’å¤±è´¥æ—¶è‡ªåŠ¨æ¸…é™¤å†å²è®°å½•ã€‚
  openai:          #å…¼å®¹æ‰€æœ‰openaiæ ‡å‡†æ¥å£ã€‚https://platform.openai.com/docs/overview
    enable_official_sdk: True   #æ˜¯å¦ä½¿ç”¨å®˜æ–¹sdkï¼Œå¦‚æœä¸ä½¿ç”¨ï¼Œåˆ™ä¸ºç›´æ¥å‘é€postè¯·æ±‚ã€‚
    api_keys:   #ç»§ç»­åƒè¿™æ ·æ·»åŠ apikey
    - YOUR_API_KEY_1
    model: deepseek-reasoner
    quest_url: https://api.deepseek.com   #å¦‚ä½¿ç”¨å®˜æ–¹sdkï¼Œåˆ™åªå¡«base_urlï¼Œå¦åˆ™å¡«å®Œæ•´urlã€‚
    temperature: 1.3
    max_tokens: 2048
    CoT: True               #æ˜¾ç¤ºæ€ç»´é“¾
    ä½¿ç”¨æ—§ç‰ˆpromptç»“æ„: false  #éƒ¨åˆ†æ¨¡å‹éœ€è¦ä½¿ç”¨æ—§ç‰ˆpromptç»“æ„
  gemini:         #https://ai.google.dev/
    api_keys:  #ç»§ç»­åƒè¿™æ ·æ·»åŠ apikey
      - YOUR_API_KEY_1
    model: gemini-2.0-flash-001
    base_url: https://generativelanguage.googleapis.com #åé¢çš„/v1/betaä»€ä¹ˆçš„ä¼šè‡ªåŠ¨å¡«å……
    temperature: 0.7
    maxOutputTokens: 2048
  è…¾è®¯å…ƒå™¨:     #æå…¶ä¸å»ºè®®ç”¨ï¼Œè…¾å­æå¾—ç©æ„ç¨€çƒ‚ï¼Œè€Œä¸”ä¸æ”¯æŒå‡½æ•°è°ƒç”¨ã€‚
    æ™ºèƒ½ä½“ID: ""
    token: ""
tts:
  tts_engine: online_vits2     #é€‰æ‹©ä½¿ç”¨çš„è¯­éŸ³åˆæˆå¼•æ“ï¼Œå¯é€‰napcat_tts/acgn_ai/vits(åœ¨ç¾¤å†…ä¸‹è½½æ•´åˆåŒ…)ï¼Œé…äº†å“ªä¸ªå¡«å“ªä¸ªã€‚
  length_limit: 100 #è¯­éŸ³åˆæˆæœ€å¤§é•¿åº¦ï¼Œè¶…è¿‡æ­¤é•¿åº¦å°†è‡ªåŠ¨æ‹’ç»åˆæˆ
  lang_type: "zh"  #è‡ªåŠ¨è½¬æ¢è¯­è¨€ç±»å‹,jaæˆ–zhã€‚vitsç³»åˆ—å»ºè®®å…¨éƒ¨ja
  online_vits2:
    speaker: "ä¸œæµ·å¸ç‹ Tokai Teio (Umamusume Pretty Derby)"   #speakerè§https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer
  online_vits:   #é…ç½®æ–¹å¼è§æ–‡æ¡£
    speaker: "å’Œæ³‰å¦ƒæ„›"
    fn_index: 3
  vits:               #æœ¬åœ°è¯­éŸ³åˆæˆï¼Œé…ç½®è¦æ±‚æä½ï¼ŒæœåŠ¡ç«¯æ•´åˆåŒ…è¯·åœ¨qç¾¤913122269ä¸‹è½½
    speaker: "ç¶¾åœ°å¯§ã€…"
    base_url: "http://127.0.0.1:5009"
  acgn_ai:
    token:           #https://getkey.acgnai.top/æ³¨å†Œåï¼Œç™»å½•è·å–ä»¤ç‰Œï¼Œæ¯ä¸ªtokenæ¯å¤©2000å­—ï¼Œæ”¯æŒå¤štoken
    - ""
    speaker: "ç²å¯ã€æ˜Ÿç©¹é“é“ã€‘"
  napcat_tts:
    character_name: "é…¥å¿ƒå¾¡å§"
  modelscope_tts:
    speaker: "ä¸œé›ªè²"
proxy:
  http_proxy: ""
  socks_proxy: ""
å¿ƒçŸ¥å¤©æ°”:
  api_key: ""     #https://www.seniverse.com/ ç”³è¯·åï¼Œå¡«ç§é’¥
image_search:
  sauceno_api_key: ""          #saucenoæœå›¾apiï¼Œä½ å¯ä»¥ä»https://saucenao.com/user.phpæ³¨å†Œå¹¶è·å–
z_library:       #å¡«ä½ çš„zlibè´¦å·ï¼Œæ­¤åŠŸèƒ½éœ€è¦å¼€å¯ä»£ç†ã€‚
  search_num: 4        #æœç´¢è¿”å›ç»“æœæ•°é‡ï¼Œé»˜è®¤4æœ¬ä¹¦
  email: ""
  password: ""  #å¿«å¡«ï¼ŒEridanusä¼šå·èµ°ä½ çš„è´¦å·å¯†ç 
youtube_asmr:
  send_type: file   #recordæˆ–è€…fileï¼Œrecordæ˜¯è¯­éŸ³ï¼Œfileæ˜¯æ–‡ä»¶
  channels:          #é¢‘é“æ¥æºã€‚æ­¤åŠŸèƒ½éœ€è¦é…ç½®proxyï¼Œå¹¶é€šè¿‡toolså®Œæˆç™»å½•ã€‚
    - '@emococh'
    - '@-gabisroom-4153'
today_wife:
  api:
  - 'http://127.0.0.1:5000/today_wife'  #ä»Šæ—¥è€å©†çš„è·å–apiï¼Œå¯ä»¥æ›¿æ¢æˆè‡ªå·±çš„å›¾åºŠï¼Œå¯ä»¥æ·»åŠ å¤šä¸ªé“¾æ¥
  - 'https://api.iw233.cn/api.php?sort=top'
  header: 'https://weibo.com/'          #çŸ¥é“çš„è‡ªå·±æ”¹ï¼Œä¸çŸ¥é“çš„ä¸è¦åŠ¨
  wifePrefix: '/'                       #é€ç¾¤å‹çš„æŒ‡ä»¤å‰ç¼€
  å¤è¯»å¼€å…³: True
  ç­¾ğŸ¦Œæ’¤å›: True
  é€ç¾¤å‹æ’¤å›: True
  é€çƒ­é—¨ç¾¤å‹: True #åªä¼šé€åˆ°æœ€è¿‘å‘è¨€è¾ƒå¤šçš„ç¾¤å‹


aiç»˜ç”»:
  sdUrl: # ä½ è‡ªå·±æ­å»ºçš„sdï¼Œåœ°å€ï¼Œç¤ºä¾‹http://127.0.0.1:17858ï¼ˆç¤ºä¾‹â‰ ä½ èƒ½ç›´æ¥å¡«ç¤ºä¾‹ç”¨ï¼‰ï¼Œå…è´¹äº‘éƒ¨ç½²è§æ–‡æ¡£ï¼Œæœ¬åœ°éƒ¨ç½²https://www.bilibili.com/video/BV1iM4y1y7oA/
    - '' 
  sdå®¡æ ¸å’Œåæ¨api: '' # å¦‚æœä½ çš„sdæœ‰åæ¨æ’ä»¶https://github.com/spawner1145/stable-diffusion-webui-wd14-tagger.gitï¼Œå¯ä»¥ç›´æ¥ä½¿ç”¨ä½ çš„sdurlçš„api
  nai_key: 
    - ''
sightengine:       #aiåˆ›ä½œå›¾ç‰‡é‰´åˆ«ï¼Œè‡ªå·±å»ç”³è¯·https://dashboard.sightengine.com/api-credentials
  api_user: ''
  api_secret: ''
nasa_api:
  api_key: ""   #nasaçš„æ¯æ—¥å¤©æ–‡api ä»https://api.nasa.gov/index.html#main-contentç”³è¯·
