bot_config:
  user_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç”¨æˆ·ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç”¨æˆ·ã€‚
  user_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç”¨æˆ·æ‰€éœ€æ“ä½œæƒé™
  group_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç¾¤ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç¾¤ã€‚
  group_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç¾¤æ‰€éœ€æ“ä½œæƒé™
  é‚€è¯·botåŠ ç¾¤æ‰€éœ€æƒé™: 0
  ç”³è¯·botå¥½å‹æ‰€éœ€æƒé™: 0
api_implements: #èŠ±é‡Œèƒ¡å“¨
   nudge:               #æˆ³ä¸€æˆ³è®¾ç½®ã€‚
     counter_probability: 100 #åå‡»æ¦‚ç‡
     replylist:       #å¦‚æœå¼€å¯aiReplyCoreï¼Œå°†ä¸ä½¿ç”¨æ­¤å¤„é…ç½®å›å¤
       - "æˆ³æˆ‘å¹²å˜›å‘€ï¼"
acg_information:
  bangumi_query_prefix: "/" #ç•ªå‰§æŸ¥è¯¢ç±»å‘½ä»¤å‰ç¼€
basic_plugin:
  setu:
    r18mode: true
    gray_layer: true #æ˜¯å¦å¼€å¯ç°åº¦å›¾åŠŸèƒ½
  tarot:
    lock: false #æ˜¯å¦å¼€å¯å¡ç‰‡é”å®šåŠŸèƒ½
    mode: "blueArchive" #ç‰Œé¢ã€‚å¯å¡« blueArchive,bilibili,AbstractImages
JMComic:            #ç¦æ¼«ç›¸å…³åŠŸèƒ½è®¾ç½®
  previewPages: 6  #éªŒè½¦é¢„è§ˆé¡µæ•°
  autoClearPDF: True #ä¸‹è½½åè‡ªåŠ¨æ¸…é™¤pdf
  savePath: "data/pictures/benzi"  #ä¸‹è½½ä¸ºpdfçš„é»˜è®¤ä¿å­˜è·¯å¾„
asmr:
  with_url: false  #æ˜¯å¦é™„å¸¦åŸå§‹éŸ³é¢‘url
  with_file: false #æ˜¯å¦åˆå¹¶å¹¶å‘é€éŸ³é¢‘æ–‡ä»¶

bili_dynamic:     #ä¸‹é¢çš„è®¾ç½®æš‚ä¸å¯ç”¨ï¼Œè¯·æš‚æ—¶ä¸è¦ä¿®æ”¹
  enable: true    #æ˜¯å¦å¼€å¯åŠ¨æ€æ¨é€åŠŸèƒ½
  dynamic_interval: 300 #åŠ¨æ€æ¨é€é—´éš”æ—¶é—´ï¼Œå•ä½ä¸ºç§’
  screen_shot_mode: "mobile" #mobileä¸ºç§»åŠ¨ç«¯æˆªå›¾ï¼Œpcä¸ºPCç«¯æˆªå›¾
  draw_type: 2    #1ä»£è¡¨ç”¨playwrightï¼ˆéœ€è¦å®‰è£…å…¶ä½™ç»„ä»¶ï¼‰ï¼›2ä»£è¡¨æœ¬åœ°Pillowç»˜å›¾ï¼ˆæœ‰å¯èƒ½å‡ºé”™ï¼‰
  is_QQ_chek: True #æ˜¯å¦æ£€æµ‹qqå°ç¨‹åºé‡Œçš„è§†é¢‘é“¾æ¥
æŠ½è±¡æ£€æµ‹:
  å¥¶é¾™æ£€æµ‹: false
  å¥¶é¾™æ’¤å›: true
  å¥¶é¾™ç¦è¨€: true
  éª‚å¥¶é¾™:
  - å¥¶é¾™æ˜¯ä½ å ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘å¥¶é¾™ï¼Ÿ
  doroæ£€æµ‹: false
  doroæ’¤å›: true
  doroç¦è¨€: true
  éª‚doro:
  - doroæ˜¯ä½ ğŸ´ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘ä½ ğŸ´çš„é—ç…§ï¼Ÿ #è‡ªå·±æ·»åŠ 
  - ç²‰è‰²å¥¶é¾™
  - å”
