bot_config:
  user_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç”¨æˆ·ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç”¨æˆ·ã€‚
  user_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç”¨æˆ·æ‰€éœ€æ“ä½œæƒé™
  group_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç¾¤ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç¾¤ã€‚
  group_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç¾¤æ‰€éœ€æ“ä½œæƒé™
  é‚€è¯·botåŠ ç¾¤æ‰€éœ€æƒé™: 0
  ç”³è¯·botå¥½å‹æ‰€éœ€æƒé™: 0
  record_mface: true #æ˜¯å¦æ”¶é›†ä¸»äººçš„è¡¨æƒ…åŒ…
api_implements: #èŠ±é‡Œèƒ¡å“¨
   nudge:               #æˆ³ä¸€æˆ³è®¾ç½®ã€‚
     counter_probability: 100 #åå‡»æ¦‚ç‡
     replylist:       #å¦‚æœå¼€å¯aiReplyCoreï¼Œå°†ä¸ä½¿ç”¨æ­¤å¤„é…ç½®å›å¤
       - "æˆ³æˆ‘å¹²å˜›å‘€ï¼"
acg_information:
  bangumi_query_prefix: "/" #ç•ªå‰§æŸ¥è¯¢ç±»å‘½ä»¤å‰ç¼€
basic_plugin:
  setu:
    r18mode: true
    download: true #å…³æ‰çš„è¯å°±æ˜¯ç›´æ¥å‘é€urlï¼Œç°åº¦å›¾ä¸ç”Ÿæ•ˆã€‚
    gray_layer: true #æ˜¯å¦å¼€å¯ç°åº¦å›¾åŠŸèƒ½
  tarot:
    lock: false #æ˜¯å¦å¼€å¯å¡ç‰‡é”å®šåŠŸèƒ½ï¼Œç°åœ¨æ²¡å†™é”å®šï¼Œå¼€äº†ä¹Ÿæ²¡ç”¨
    mode: "blueArchive" #ç‰Œé¢ã€‚å¯å¡« blueArchive,bilibili,AbstractImages
    å½©è›‹ç‰Œ:
      enable: true #æ˜¯å¦å¼€å¯å½©è›‹ç‰Œ
      probability: 5 #å½©è›‹ç‰Œå‡ºç°æ¦‚ç‡
      card_index:
        - data/pictures/tarot/hidden_tarot/dio.jpg: ""
        - data/pictures/tarot/hidden_tarot/GIOGIO.jpg: ""
        - data/pictures/tarot/hidden_tarot/gyro.jpg: ""
        - data/pictures/tarot/hidden_tarot/hp.jpg: ""
        - data/pictures/tarot/hidden_tarot/johnny.jpg: ""
        - data/pictures/tarot/hidden_tarot/joseph.jpg: ""
        - data/pictures/tarot/hidden_tarot/vlt.jpg: ""
  æœå›¾:
    èšåˆæœå›¾: true          #æœå•å›¾
    soutu_bot: true       #æœæœ¬å­
  ç»˜å›¾æ¡†æ¶:
    gal_recommend: True   #galgameæ¨èæ˜¯å¦æ¥å…¥ç»˜å›¾æ¡†æ¶ï¼Œè‹¥falseåˆ™èŠå¤©è®°å½•å‘é€
    majsoul_search: True  #é›€é­‚æœç´¢åŠŸèƒ½æ˜¯å¦æ¥å…¥ç»˜å›¾æ¡†æ¶ï¼Œè‹¥falseåˆ™æ–‡å­—å‘é€

JMComic:                  #ç¦æ¼«ç›¸å…³åŠŸèƒ½è®¾ç½®
  anti_nsfw: black_and_white   #é˜²åç­–ç•¥ï¼Œå¯é€‰gifã€black_and_whiteã€no_censor
  gif_compress: false     #gifæ¨¡å¼ä¸‹æ˜¯å¦å‹ç¼©
  previewPages: 6         #éªŒè½¦é¢„è§ˆé¡µæ•°
  autoClearPDF: True      #ä¸‹è½½åè‡ªåŠ¨æ¸…é™¤pdf
  savePath: "data/pictures/benzi"  #ä¸‹è½½ä¸ºpdfçš„é»˜è®¤ä¿å­˜è·¯å¾„
asmr:
  with_url: false  #æ˜¯å¦é™„å¸¦åŒä½œå“é›†å…¶ä»–ä½œå“çš„url
  with_file: false #æ˜¯å¦åˆå¹¶å¹¶å‘é€éŸ³é¢‘æ–‡ä»¶
  max_merge_file_num: 10 #æœ€å¤§åˆå¹¶æ–‡ä»¶æ•°
  gray_layer: true #æ˜¯å¦å¼€å¯ç°åº¦å›¾åŠŸèƒ½

bili_dynamic:     #ä¸‹é¢çš„è®¾ç½®æš‚ä¸å¯ç”¨ï¼Œè¯·æš‚æ—¶ä¸è¦ä¿®æ”¹
  enable: true    #æ˜¯å¦å¼€å¯åŠ¨æ€æ¨é€åŠŸèƒ½
  dynamic_interval: 300 #åŠ¨æ€æ¨é€é—´éš”æ—¶é—´ï¼Œå•ä½ä¸ºç§’
  screen_shot_mode: "mobile" #mobileä¸ºç§»åŠ¨ç«¯æˆªå›¾ï¼Œpcä¸ºPCç«¯æˆªå›¾
  draw_type: 2    #1ä»£è¡¨ç”¨playwrightï¼ˆéœ€è¦å®‰è£…å…¶ä½™ç»„ä»¶ï¼‰ï¼›2ä»£è¡¨æœ¬åœ°Pillowç»˜å›¾ï¼ˆæœ‰å¯èƒ½å‡ºé”™ï¼‰
  is_QQ_chek: True #æ˜¯å¦æ£€æµ‹qqå°ç¨‹åºé‡Œçš„è§†é¢‘é“¾æ¥

ç½‘æ˜“äº‘å¡ç‰‡:    #ç»˜åˆ¶ç½‘æ˜“äº‘æ­Œæ›²åˆ†äº«å¡ç‰‡
  enable: true
  è§£æè‡ªå¸¦éŸ³é¢‘ä¸‹è½½url: false #æ¶‰åŠä»˜è´¹éŸ³ä¹ç‰ˆæƒé—®é¢˜ï¼Œåªèƒ½ä»¥æ–‡ä»¶å½¢å¼å‘é€äº†,ä¸å…è®¸è¿›è¡Œä¼ æ’­ã€é”€å”®ç­‰å•†ä¸šæ´»åŠ¨!!

æŠ½è±¡æ£€æµ‹:
  å¥¶é¾™æ£€æµ‹: false
  å¥¶é¾™æ’¤å›: true
  å¥¶é¾™ç¦è¨€: true
  éª‚å¥¶é¾™:
  - å¥¶é¾™æ˜¯ä½ å ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘å¥¶é¾™ï¼Ÿ
  doroæ£€æµ‹: false
  doroæ’¤å›: true
  doroç¦è¨€: true
  éª‚doro:
  - doroæ˜¯ä½ ğŸ´ï¼Ÿè¿™ä¹ˆå–œæ¬¢å‘ä½ ğŸ´çš„é—ç…§ï¼Ÿ #è‡ªå·±æ·»åŠ 
  - ç²‰è‰²å¥¶é¾™
  - å”
  ç”·å¨˜æ£€æµ‹: false
  ç”·å¨˜æ’¤å›: true
  ç”·å¨˜ç¦è¨€: true
  éª‚ç”·å¨˜:
  - å‘ç”·å¨˜å›¾ç»™ä½ è¶…å¸‚
scheduledTasks:    #å…¶ä»–å®šæ—¶ä»»åŠ¡æ¨¡å—çš„å†…å®¹ä¼šé™†ç»­è½¬åˆ°è¿™é‡Œ
  æ—©å®‰é—®å€™:         #æ™¨é—´æ¨é€
    enable: true  #å‘ä¿¡ä»»ç”¨æˆ·æ¨é€å¤©æ°”ä¿¡æ¯
    time: 8/3      #æ¨é€æ—¶é—´
    trustThreshold: 9 #æƒé™ç­‰çº§è¦æ±‚ï¼Œä½äºæ­¤å€¼çš„ç”¨æˆ·å°†ä¸ä¼šè¢«æ¨é€
    onlyTrustUser: True  #ä»…å‘ä¿¡ä»»ç”¨æˆ·æ¨é€
  æ™šå®‰é—®å€™: #æ™šå®‰æç¤º
    enable: true
    text: æ™šå®‰ï¼    #å¼€å¯aiReplyCoreåï¼Œæ­¤é¡¹å°†è¢«aiæ›¿ä»£
    time: 22/31
    trustThreshold: 9 #ä½äºæƒé™ç­‰çº§çš„ç”¨æˆ·å°†ä¸ä¼šè¢«æ¨é€
    onlyTrustUser: True  #ä»…å‘ä¿¡ä»»ç”¨æˆ·æ¨é€
  bangumi:         #bangumiæ¨é€
    enable: True
    text: "æ™šä¸Šå¥½ï¼Œè¿™é‡Œæ˜¯ä»Šå¤©çš„bangumiæ¨é€"
    time: 19/16
  æ¯æ—¥å¤©æ–‡:       #nasaå¤©æ–‡æ¨é€
    enable: True
    text: "ä»Šæ—¥nasaå¤©æ–‡æ¨é€"
    time: 18/59
  å•å‘å†:      #å•å‘å†
    enable: true
    text: ä»Šæ—¥å•å‘å†
    time: 19/2
  æ‘¸é±¼äººæ—¥å†:            #æ‘¸é±¼äººæ—¥å†
    enable: true
    text: çœŸæ²¡ç”¨å•Šï¼Œåˆåœ¨æ‘¸é±¼äº†å§ï¼Œæ‚é±¼â¤
    time: 17/30
  æ–°é—»:            #æ–°é—»
    enable: true
    text: æ—©ä¸Šå¥½æ‚é±¼â¤ï¼Œè¿™é‡Œæ˜¯ä»Šå¤©çš„æ–°é—»
    time: 8/2
  å…è´¹æ¸¸æˆå–œåŠ ä¸€:       #å…è´¹æ¸¸æˆæç¤º
    enable: true
    text: æ‚é±¼â¤æ¥ç™½å«–æ¸¸æˆäº†
    time: 12/2
  nightASMR:
    enable: true
    text: å¬å®Œå°±èµ¶ç´§ç¡è§‰å§~ç¥ä½ å¥½æ¢¦ï¼(â‰§â–½â‰¦*)
    time: 22/35
  bingæ¯æ—¥å›¾åƒ:
    enable: true
    time: 10/2
